# Generated by Django 6.1.1 on 2026-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=200)),
                ('e_id', models.CharField(max_length=15)),
                ('e_email', models.EmailField(max_length=200)),
                ('e_department', models.CharField(max_length=200)),
                ('e_job_role', models.CharField(max_length=200)),
                ('e_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_date_of_joining', models.DateField()),
                ('e_currently_working_or_not', models.BooleanField(default=True)),
            ],
        ),
    ]
