# Generated by Django 6.1.1 on 2026-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_duration', models.IntegerField()),
                ('c_fees', models.IntegerField()),
                ('c_trainer_name', models.CharField(max_length=200)),
                ('c_mode_online_or_offline', models.CharField(max_length=200)),
                ('c_start_date', models.DateField()),
                ('c_number_of_seats', models.IntegerField()),
                ('c_course_active_or_inactive', models.BooleanField(default=True)),
            ],
        ),
    ]
