# Generated by Django 6.1.1 on 2026-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_code', models.CharField(max_length=15)),
                ('p_category', models.CharField(max_length=200)),
                ('p_price', models.IntegerField()),
                ('p_stock_quantity', models.IntegerField()),
                ('p_description', models.TextField()),
                ('p_avaiable_or_not', models.BooleanField(default=True)),
                ('p_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
